# name: 'teacher-schedule-dashboard'

services:

  web:
    build: app
    restart: always
    expose:
      - 5001
    env_file:
      - ./.env.prod
    environment:
      - VIRTUAL_HOST=teacher.sam-projekte.de
      - LETSENCRYPT_HOST=teacher.sam-projekte.de
      - LETSENCRYPT_EMAIL=uk@science-and-more.de
    command: gunicorn --bind 0.0.0.0:5001 app:app
    depends_on:
      - mongo
    networks:
      - webproxy

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - /opt/mongo-data:/data/db  # persist MongoDB data
    networks:
      - webproxy
    ports:
      - "27017:27017"

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webproxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - webproxy

  

networks:
  webproxy:
    driver: bridge

