# name: 'teacher-schedule-dashboard'

services:
  web:
    build: app
    restart: always
    expose:
      - 5001
    env_file:
      - ./.env.prod
    command: gunicorn --bind 0.0.0.0:5001 app:app
    depends_on:
      - mongo
    networks:
      - all-apps-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - /opt/mongo-data:/data/db  # persist MongoDB data
    networks:
      - all-apps-network
    ports:
      - "27017:27017"

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - all-apps-network

networks:
  all-apps-network:
    driver: bridge

