# name: 'teacher-schedule-dashboard'

services:
  web:
    build: app
    restart: always
    expose:
      - 5001
    env_file:
      - ./.env.prod
    environment:
      - VIRTUAL_HOST=teacher.sam-projekte.de
      - LETSENCRYPT_HOST=teacher.sam-projekte.de
      - LETSENCRYPT_EMAIL=uk@science-and-more.de
    command: gunicorn --bind 0.0.0.0:5001 app:app
    depends_on:
      - mongo
    networks:
      - all-apps-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - /opt/mongo-data:/data/db  # persist MongoDB data
    networks:
      - all-apps-network
    ports:
      - "27017:27017"

  nginx:
    build: ./services/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./services/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./services/certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - all-apps-network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx
    environment:
      - DEFAULT_EMAIL=uk@science-and-more.de
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/certs:/etc/nginx/certs
      - ./services/acme:/etc/acme.sh
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - web

networks:
  all-apps-network:
    driver: bridge

