# name: 'teacher-schedule-dashboard'

services:
  web:
    build: app
    restart: always
    expose:
      - 5001
    env_file:
      - ./.env.dev
      - ./.env.db
    command: gunicorn --bind 0.0.0.0:5001 app:app
    volumes:
      - uploads:/app/data
    depends_on:
      - db
    networks:
      - all-apps-network

  db:
    image: postgres:15
    container_name: pg-db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - all-apps-network
    ports:
      - "5432:5432"

  nginx:
    #build: ./services/nginx
    image: nginx:alpine
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./services/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - all-apps-network

networks:
  all-apps-network:
    driver: bridge

volumes:
  pg_data:
  uploads:
    driver: local

