# name: 'teacher-schedule-dashboard'

services:
  web:
    build: app
    restart: always
    expose:
      - 5001
    env_file:
      - ./.env.dev
    command: gunicorn --bind 0.0.0.0:5001 app:app
    volumes:
      - uploads:/app/data
    depends_on:
      - mongo
    networks:
      - all-apps-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - /opt/mongo-data:/data/db  # persist MongoDB data
    networks:
      - all-apps-network
    ports:
      - "27017:27017"

  nginx:
    #build: ./services/nginx
    image: nginx:alpine
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./services/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - all-apps-network

networks:
  all-apps-network:
    driver: bridge

volumes:
  uploads:
    driver: local

