# name: 'teacher-schedule-dashboard'

services:

  web:
    build: app
    restart: always
    expose:
      - 5001
    env_file:
      - ./.env.prod
    environment:
      - VIRTUAL_HOST=teacher.sam-projekte.de
      - LETSENCRYPT_HOST=teacher.sam-projekte.de
      - LETSENCRYPT_EMAIL=uk@science-and-more.de
    command: gunicorn --bind 0.0.0.0:5001 app:app
    volumes:
      - uploads:/app/data
    depends_on:
      - db
    networks:
      - webproxy

  db:
    image: postgres:15
    container_name: pg-db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - webproxy
    ports:
      - "5432:5432"

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro  # nginx-proxy
    networks:
      - webproxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - webproxy

  

networks:
  webproxy:
    driver: bridge

volumes:
  certs:
  vhost:
  html:
  uploads:
  pg_data:
